# Generated by Django 5.0.14 on 2025-12-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Publicado', 'Publicado')], default='Rascunho', max_length=20),
        ),
    ]
